/**
 * Curated registry of popular MCP servers.
 * Used by the MCP Hub UI to browse and install servers.
 */
export const MCP_REGISTRY = [
  {
    id: 'brave-search',
    name: 'Brave Search',
    description: 'Web search and content extraction via Brave Search API',
    category: 'search',
    url: 'https://mcp.brave.com/sse',
    transport: 'sse',
    requiresKey: true,
    keyEnvVar: 'BRAVE_API_KEY',
    keyUrl: 'https://brave.com/search/api/',
  },
  {
    id: 'tavily',
    name: 'Tavily Search',
    description: 'AI-powered web search optimized for LLMs',
    category: 'search',
    url: 'https://mcp.tavily.com/mcp',
    transport: 'http',
    requiresKey: true,
    keyEnvVar: 'TAVILY_API_KEY',
    keyUrl: 'https://tavily.com/',
  },
  {
    id: 'exa',
    name: 'Exa Search',
    description: 'Neural search engine for finding relevant content',
    category: 'search',
    url: 'https://mcp.exa.ai/mcp',
    transport: 'http',
    requiresKey: true,
    keyEnvVar: 'EXA_API_KEY',
    keyUrl: 'https://exa.ai/',
  },
  {
    id: 'firecrawl',
    name: 'Firecrawl',
    description: 'Web scraping and crawling with structured output',
    category: 'web',
    url: 'https://mcp.firecrawl.dev/sse',
    transport: 'sse',
    requiresKey: true,
    keyEnvVar: 'FIRECRAWL_API_KEY',
    keyUrl: 'https://firecrawl.dev/',
  },
  {
    id: 'browserbase',
    name: 'Browserbase',
    description: 'Cloud browser automation for web scraping and testing',
    category: 'web',
    url: 'https://mcp.browserbase.com/mcp',
    transport: 'http',
    requiresKey: true,
    keyEnvVar: 'BROWSERBASE_API_KEY',
    keyUrl: 'https://browserbase.com/',
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Access GitHub repos, issues, PRs, and code search',
    category: 'dev',
    npmPackage: '@modelcontextprotocol/server-github',
    transport: 'stdio',
    requiresKey: true,
    keyEnvVar: 'GITHUB_TOKEN',
    keyUrl: 'https://github.com/settings/tokens',
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Project management: issues, projects, and cycles',
    category: 'dev',
    url: 'https://mcp.linear.app/sse',
    transport: 'sse',
    requiresKey: true,
    keyEnvVar: 'LINEAR_API_KEY',
    keyUrl: 'https://linear.app/settings/api',
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Read and send Slack messages, manage channels',
    category: 'communication',
    npmPackage: '@modelcontextprotocol/server-slack',
    transport: 'stdio',
    requiresKey: true,
    keyEnvVar: 'SLACK_BOT_TOKEN',
    keyUrl: 'https://api.slack.com/apps',
  },
  {
    id: 'filesystem',
    name: 'Filesystem',
    description: 'Read and write files on the local filesystem',
    category: 'system',
    npmPackage: '@modelcontextprotocol/server-filesystem',
    transport: 'stdio',
    requiresKey: false,
  },
  {
    id: 'memory',
    name: 'Memory',
    description: 'Persistent knowledge graph memory for LLMs',
    category: 'system',
    npmPackage: '@modelcontextprotocol/server-memory',
    transport: 'stdio',
    requiresKey: false,
  },
  {
    id: 'postgres',
    name: 'PostgreSQL',
    description: 'Query and manage PostgreSQL databases',
    category: 'database',
    npmPackage: '@modelcontextprotocol/server-postgres',
    transport: 'stdio',
    requiresKey: true,
    keyEnvVar: 'POSTGRES_URL',
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    description: 'Query and manage SQLite databases',
    category: 'database',
    npmPackage: '@modelcontextprotocol/server-sqlite',
    transport: 'stdio',
    requiresKey: false,
  },
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Error tracking and performance monitoring',
    category: 'monitoring',
    url: 'https://mcp.sentry.dev/sse',
    transport: 'sse',
    requiresKey: true,
    keyEnvVar: 'SENTRY_AUTH_TOKEN',
    keyUrl: 'https://sentry.io/settings/auth-tokens/',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    description: 'Manage Cloudflare Workers, KV, R2, and D1',
    category: 'cloud',
    npmPackage: '@cloudflare/mcp-server-cloudflare',
    transport: 'stdio',
    requiresKey: true,
    keyEnvVar: 'CLOUDFLARE_API_TOKEN',
    keyUrl: 'https://dash.cloudflare.com/profile/api-tokens',
  },
];

export const MCP_CATEGORIES = [
  { id: 'search', name: 'Search', color: 'blue' },
  { id: 'web', name: 'Web', color: 'orange' },
  { id: 'dev', name: 'Developer', color: 'purple' },
  { id: 'communication', name: 'Communication', color: 'green' },
  { id: 'system', name: 'System', color: 'gray' },
  { id: 'database', name: 'Database', color: 'cyan' },
  { id: 'monitoring', name: 'Monitoring', color: 'yellow' },
  { id: 'cloud', name: 'Cloud', color: 'indigo' },
];
